# Generated by Django 2.1.4 on 2018-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
